apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: demos.wubw.fun
spec:
  group: wubw.fun
  scope: Cluster
  names:
    kind: Demo
    plural: demos
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                param1:
                  type: string
